# A small list of example (text, intent) pairs. Add more examples if you want.
examples_initial = [
    ("hi", "greeting"),
    ("hello there", "greeting"),
    ("good morning", "greeting"),
    ("bye", "goodbye"),
    ("see you later", "goodbye"),
    ("what is the price of product x?", "pricing"),
    ("how much does this cost?", "pricing"),
    ("i want to apply for the job", "apply"),
    ("how can i submit my CV?", "apply"),
    ("i need help with my account", "support"),
    ("my transaction failed", "support"),
    ("tell me a joke", "smalltalk"),
    ("are you a human?", "smalltalk"),
    ("what is the weather today?", "smalltalk"),
    ("i suspect fraud in my account", "fraud"),
    ("there is an unknown charge", "fraud"),
    ("thanks, that helped", "feedback_positive"),
    ("no, that is not what i asked", "feedback_negative"),
]


# More synthetic data generateed locally with DeepSeek-r1- llama distilled
examples_extended = [
    ("Hi there", "greeting"),
    ("Hello", "greeting"),
    ("Good day", "greeting"),
    ("How are you?", "greeting"),
    ("Nice to meet you", "greeting"),
    ("Welcome!", "greeting"),
    ("Hi everyone", "greeting"),
    ("Greeting", "greeting"),
    ("Hi folks", "greeting"),
    ("Hi friends", "greeting"),
    ("Bye for now", "goodbye"),
    ("Take care", "goodbye"),
    ("See ya later", "goodbye"),
    ("Farewell", "goodbye"),
    ("Don't forget to come back", "goodbye"),
    ("Goodbye for today", "goodbye"),
    ("Not goodbye, see you soon", "goodbye"),
    ("Adios", "goodbye"),
    ("Ciao", "goodbye"),
    ("Auf Wiedersehen", "goodbye"),
    ("What's the price of this?", "pricing"),
    ("How much does it cost?", "pricing"),
    ("Are prices fixed?", "pricing"),
    ("Can I get a discount?", "pricing"),
    ("How expensive is this item?", "pricing"),
    ("Is there a membership fee?", "pricing"),
    ("What are the features included?", "pricing"),
    ("How much for the upgrade?", "pricing"),
    ("Pricing plan details needed", "pricing"),
    ("Cost inquiry", "pricing"),
    ("I want to apply for the job", "apply"),
    ("How do I apply?", "apply"),
    ("Applying for the position", "apply"),
    ("Need help with application", "apply"),
    ("When can I submit my CV?", "apply"),
    ("Job application process", "apply"),
    ("How to get hired", "apply"),
    ("Looking to apply", "apply"),
    ("Assistance in applying", "apply"),
    ("Application questions", "apply"),
    ("My account isn't working", "support"),
    ("I have an issue with my payment", "support"),
    ("Can someone help me?", "support"),
    ("I need technical support", "support"),
    ("Something's wrong with my subscription", "support"),
    ("Support request", "support"),
    ("Help needed immediately", "support"),
    ("Tech support please", "support"),
    ("Subscription issues", "support"),
    ("Assistance required", "support"),
    ("There's a suspicious charge", "fraud"),
    ("Strange activity on my account", "fraud"),
    ("Unauthorized transaction detected", "fraud"),
    ("Something seems off", "fraud"),
    ("I suspect fraud.", "fraud"),
    ("Fraud alert", "fraud"),
    ("Unusual account behavior", "fraud"),
    ("Odd transactions", "fraud"),
    ("Security concern", "fraud"),
    ("Fraud detection needed", "fraud"),
    ("Loved the service!", "feedback_positive"),
    ("Excellent support!", "feedback_positive"),
    ("Great experience!", "feedback_positive"),
    ("Super helpful.", "feedback_positive"),
    ("Highly satisfied!", "feedback_positive"),
    ("Positive feedback", "feedback_positive"),
    ("Wonderful support", "feedback_positive"),
    ("Exceptional service", "feedback_positive"),
    ("Satisfied with help", "feedback_positive"),
    ("Top-notch assistance", "feedback_positive"),
    ("Disappointed with service", "feedback_negative"),
    ("Not happy with response", "feedback_negative"),
    ("Poor assistance received", "feedback_negative"),
    ("Unhelpful reply", "feedback_negative"),
    ("Terrible experience.", "feedback_negative"),
    ("Bad support interaction", "feedback_negative"),
    ("Negative feedback", "feedback_negative"),
    ("Dissatisfaction", "feedback_negative"),
    ("Unhappy with outcome", "feedback_negative"),
    ("Poor resolution", "feedback_negative"),
    ("What's the time?", "smalltalk"),
    ("Can you tell me the weather?", "smalltalk"),
    ("Joke please?", "smalltalk"),
    ("Are you free later?", "smalltalk"),
    ("Just making small talk.", "smalltalk"),
    ("How are things going?", "smalltalk"),
    ("Chatting away!", "smalltalk"),
    ("Light conversation", "smalltalk"),
    ("Random thoughts", "smalltalk"),
    ("Casual banter", "smalltalk"),
]


# Even bigger dataset generated wiht Hermes4 405b model
examples_500 = [
    # Greeting (50 examples)
    ("Hey, how's it going?", "greeting"),
    ("What's up?", "greeting"),
    ("Good morning!", "greeting"),
    ("Nice to see you again.", "greeting"),
    ("Long time no talk!", "greeting"),
    ("Greetings and salutations!", "greeting"),
    ("Hey there, stranger!", "greeting"),
    ("Welcome back!", "greeting"),
    ("Top of the morning to you!", "greeting"),
    ("Howdy!", "greeting"),
    ("Good afternoon!", "greeting"),
    ("Pleasure to make your acquaintance", "greeting"),
    ("Hello there!", "greeting"),
    ("Hey folks!", "greeting"),
    ("What's happening?", "greeting"),
    ("Salutations!", "greeting"),
    ("How's everything?", "greeting"),
    ("Good to see you", "greeting"),
    ("Hiya!", "greeting"),
    ("Welcome!", "greeting"),
    ("How are things?", "greeting"),
    ("Hey everyone!", "greeting"),
    ("Good evening!", "greeting"),
    ("Well hello!", "greeting"),
    ("How's your day?", "greeting"),
    ("Hey!", "greeting"),
    ("What's new?", "greeting"),
    ("Greetings from afar!", "greeting"),
    ("Hi there!", "greeting"),
    ("Good to be back!", "greeting"),
    ("How's life treating you?", "greeting"),
    ("Welcome friend!", "greeting"),
    ("Hey you!", "greeting"),
    ("Greetings!", "greeting"),
    ("How's it hanging?", "greeting"),
    ("Hey, what's up?", "greeting"),
    ("Good day to you!", "greeting"),
    ("Hello friend!", "greeting"),
    ("How's your week going?", "greeting"),
    ("Welcome to the conversation!", "greeting"),
    ("Hi there, how are you?", "greeting"),
    ("Good to see you again!", "greeting"),
    ("Hey, long time no see!", "greeting"),
    ("How's your morning been?", "greeting"),
    ("Welcome back, we missed you!", "greeting"),
    ("Hello hello!", "greeting"),
    ("How's your day going?", "greeting"),
    ("Hey there, how's it going?", "greeting"),
    ("Good to have you here!", "greeting"),
    ("How's everything with you?", "greeting"),
    ("Welcome to the chat!", "greeting"),
    ("Hey, how have you been?", "greeting"),
    # Goodbye (40 examples)
    ("Talk to you later!", "goodbye"),
    ("Have a nice day!", "goodbye"),
    ("Until next time.", "goodbye"),
    ("Catch you on the flip side.", "goodbye"),
    ("Goodnight!", "goodbye"),
    ("Take it easy.", "goodbye"),
    ("See you around.", "goodbye"),
    ("Cheers!", "goodbye"),
    ("Have a good one.", "goodbye"),
    ("Later!", "goodbye"),
    ("Peace out!", "goodbye"),
    ("Until we meet again", "goodbye"),
    ("Take care now!", "goodbye"),
    ("Bye-bye!", "goodbye"),
    ("So long!", "goodbye"),
    ("Farewell for now", "goodbye"),
    ("Have a wonderful day", "goodbye"),
    ("See you later, alligator!", "goodbye"),
    ("Catch you later!", "goodbye"),
    ("Stay safe out there", "goodbye"),
    ("Goodbye and good luck!", "goodbye"),
    ("Until next time!", "goodbye"),
    ("Have a pleasant evening", "goodbye"),
    ("Take care of yourself", "goodbye"),
    ("Bye for now!", "goodbye"),
    ("See ya!", "goodbye"),
    ("Au revoir!", "goodbye"),
    ("Have a great week!", "goodbye"),
    ("Farewell!", "goodbye"),
    ("Goodbye everyone!", "goodbye"),
    ("Take it easy out there", "goodbye"),
    ("Until we chat again", "goodbye"),
    ("Have a fantastic day!", "goodbye"),
    ("See you on the other side!", "goodbye"),
    ("Goodbye and take care!", "goodbye"),
    ("So long for now", "goodbye"),
    ("Until next time, folks!", "goodbye"),
    ("Have a safe journey!", "goodbye"),
    ("Goodbye and thanks!", "goodbye"),
    ("Later alligator!", "goodbye"),
    ("Farewell friends!", "goodbye"),
    # Pricing (50 examples)
    ("Do you offer a free trial?", "pricing"),
    ("What's the cost after the trial ends?", "pricing"),
    ("Are there any hidden fees?", "pricing"),
    ("Can I get a refund if unsatisfied?", "pricing"),
    ("How much is the monthly subscription?", "pricing"),
    ("Is there a discount for annual payment?", "pricing"),
    ("What payment methods do you accept?", "pricing"),
    ("Do prices vary by region?", "pricing"),
    ("Are there any setup fees?", "pricing"),
    ("Can I upgrade my plan later?", "pricing"),
    ("What's included in the premium package?", "pricing"),
    ("How much for additional users?", "pricing"),
    ("Do you offer student discounts?", "pricing"),
    ("Is there a money-back guarantee?", "pricing"),
    ("What's the price difference between plans?", "pricing"),
    ("Are there any cancellation fees?", "pricing"),
    ("How much does international shipping cost?", "pricing"),
    ("Do you have bulk pricing options?", "pricing"),
    ("What's the cost for premium features?", "pricing"),
    ("Are there any ongoing maintenance fees?", "pricing"),
    ("Can I downgrade my subscription anytime?", "pricing"),
    ("What's the price for enterprise solutions?", "pricing"),
    ("Do you offer non-profit discounts?", "pricing"),
    ("How much for the basic package?", "pricing"),
    ("Are there any taxes not included?", "pricing"),
    ("What's the cost for additional storage?", "pricing"),
    ("Can I get a custom quote?", "pricing"),
    ("Do you offer military discounts?", "pricing"),
    ("What's the price for priority support?", "pricing"),
    ("Are there any early termination fees?", "pricing"),
    ("How much is the setup cost?", "pricing"),
    ("Do you have family plan pricing?", "pricing"),
    ("What's the educational pricing?", "pricing"),
    ("Are there any per-user fees?", "pricing"),
    ("Can I pause my subscription?", "pricing"),
    ("What's the price for API access?", "pricing"),
    ("Do you offer senior citizen discounts?", "pricing"),
    ("How much for the pro version?", "pricing"),
    ("Are there any data overage charges?", "pricing"),
    ("What's the cost for extra bandwidth?", "pricing"),
    ("Can I get a prorated refund?", "pricing"),
    ("Do you offer volume licensing?", "pricing"),
    ("What's the price for white-label solutions?", "pricing"),
    ("Are there any minimum contract lengths?", "pricing"),
    ("How much for expedited shipping?", "pricing"),
    ("Do you have a pay-as-you-go option?", "pricing"),
    # Apply (40 examples)
    ("Where can I find the job listing?", "apply"),
    ("What documents are needed for the application?", "apply"),
    ("Is there an age requirement?", "apply"),
    ("How long does the hiring process take?", "apply"),
    ("Can I apply for multiple positions?", "apply"),
    ("Do you sponsor work visas?", "apply"),
    ("What's the next step after submitting the CV?", "apply"),
    ("Are internships available?", "apply"),
    ("Required qualifications for the role?", "apply"),
    ("Application deadline extended?", "apply"),
    ("Can I submit a video resume?", "apply"),
    ("What's the status of my application?", "apply"),
    ("Do you require references?", "apply"),
    ("Is a cover letter mandatory?", "apply"),
    ("How should I format my resume?", "apply"),
    ("Are remote positions available?", "apply"),
    ("What's the application deadline?", "apply"),
    ("Can I apply through LinkedIn?", "apply"),
    ("Do you conduct background checks?", "apply"),
    ("How many rounds of interviews?", "apply"),
    ("What's the starting salary range?", "apply"),
    ("Are there any required certifications?", "apply"),
    ("Can I reapply if rejected?", "apply"),
    ("Do you offer relocation assistance?", "apply"),
    ("What's the company culture like?", "apply"),
    ("Are part-time positions available?", "apply"),
    ("How soon can I start if selected?", "apply"),
    ("Do you require a portfolio?", "apply"),
    ("What's the dress code for interviews?", "apply"),
    ("Are there any required skills tests?", "apply"),
    ("Can I apply in person?", "apply"),
    ("Do you offer tuition reimbursement?", "apply"),
    ("What benefits come with the position?", "apply"),
    ("Are there growth opportunities?", "apply"),
    ("How should I prepare for the interview?", "apply"),
    ("Do you have diversity programs?", "apply"),
    ("What's the team structure like?", "apply"),
    ("Are there any language requirements?", "apply"),
    ("Can I negotiate the salary?", "apply"),
    ("What's the typical career path here?", "apply"),
    ("Do you provide equipment for remote work?", "apply"),
    # Support (100 examples)
    ("My order hasn't arrived yet.", "support"),
    ("The website is down.", "support"),
    ("I can't access my dashboard.", "support"),
    ("Need help resetting my password.", "support"),
    ("The app keeps crashing.", "support"),
    ("I'm having trouble with checkout.", "support"),
    ("My payment method is being declined.", "support"),
    ("Subscription renewal failed.", "support"),
    ("Can't download the latest update.", "support"),
    ("Error message when saving changes.", "support"),
    ("My account was suspended.", "support"),
    ("Can't log in to my account.", "support"),
    ("The video isn't loading.", "support"),
    ("Need help with two-factor authentication.", "support"),
    ("My files won't sync.", "support"),
    ("The sound isn't working.", "support"),
    ("Getting error code 404.", "support"),
    ("My profile picture won't upload.", "support"),
    ("Can't connect to the server.", "support"),
    ("The printer isn't responding.", "support"),
    ("My microphone isn't detected.", "support"),
    ("The software is running slowly.", "support"),
    ("Can't access my email.", "support"),
    ("The keyboard isn't working.", "support"),
    ("My screen is frozen.", "support"),
    ("The website loads slowly.", "support"),
    ("Can't make a purchase.", "support"),
    ("The touch screen isn't responding.", "support"),
    ("My account was hacked.", "support"),
    ("The battery drains too quickly.", "support"),
    ("Can't receive verification code.", "support"),
    ("The app won't open.", "support"),
    ("My order was damaged.", "support"),
    ("The camera isn't focusing.", "support"),
    ("Can't reset my password.", "support"),
    ("The microphone has static.", "support"),
    ("My controller isn't connecting.", "support"),
    ("The website is showing errors.", "support"),
    ("Can't update my payment information.", "support"),
    ("The headphones won't pair.", "support"),
    ("My account is locked.", "support"),
    ("The screen is flickering.", "support"),
    ("Can't download attachments.", "support"),
    ("The keyboard is unresponsive.", "support"),
    ("My device won't charge.", "support"),
    ("The app crashes on startup.", "support"),
    ("Can't access my cloud storage.", "support"),
    ("The touchpad isn't working.", "support"),
    ("My subscription was canceled.", "support"),
    ("The speakers have no sound.", "support"),
    ("Can't connect to Wi-Fi.", "support"),
    ("The software won't install.", "support"),
    ("My order status says pending.", "support"),
    ("The screen has dead pixels.", "support"),
    ("Can't verify my account.", "support"),
    ("The battery won't hold a charge.", "support"),
    ("My product arrived broken.", "support"),
    ("The app freezes constantly.", "support"),
    ("Can't make international calls.", "support"),
    ("The keyboard types wrong characters.", "support"),
    ("My account was deactivated.", "support"),
    ("The printer is offline.", "support"),
    ("Can't access my purchased content.", "support"),
    ("The microphone picks up static.", "support"),
    ("My controller input is delayed.", "support"),
    ("The website won't load images.", "support"),
    ("Can't update my profile information.", "support"),
    ("The headphones have poor sound quality.", "support"),
    ("My account was restricted.", "support"),
    ("The screen has discoloration.", "support"),
    ("Can't download files from email.", "support"),
    ("The keyboard backlight isn't working.", "support"),
    ("My device overheats.", "support"),
    ("The app won't connect to the internet.", "support"),
    ("Can't access my backup files.", "support"),
    ("The touchpad is too sensitive.", "support"),
    ("My subscription was charged twice.", "support"),
    ("The speakers crackle at high volume.", "support"),
    ("Can't connect to Bluetooth.", "support"),
    ("The software has compatibility issues.", "support"),
    ("My order tracking number is invalid.", "support"),
    ("The screen has lines across it.", "support"),
    ("Can't verify my identity.", "support"),
    ("The battery drains while charging.", "support"),
    ("My product is defective.", "support"),
    ("The app crashes when saving.", "support"),
    ("Can't make video calls.", "support"),
    ("The keyboard misses keystrokes.", "support"),
    ("My account was suspended without reason.", "support"),
    ("The printer jams paper.", "support"),
    # Fraud (80 examples)
    ("There's a charge I don't recognize.", "fraud"),
    ("My account was accessed from another country.", "fraud"),
    ("Received a phishing email claiming to be you.", "fraud"),
    ("Someone changed my password without consent.", "fraud"),
    ("Unusual login attempts detected.", "fraud"),
    ("My card was used without permission.", "fraud"),
    ("Suspicious withdrawal from my account.", "fraud"),
    ("Fake invoice received.", "fraud"),
    ("Identity theft concern.", "fraud"),
    ("Fraudulent transaction reported.", "fraud"),
    ("Unauthorized access to my account.", "fraud"),
    ("Phishing attempt detected.", "fraud"),
    ("Suspicious login from unknown device.", "fraud"),
    ("Unrecognized transaction on my statement.", "fraud"),
    ("Stolen credit card used on my account.", "fraud"),
    ("Fraud alert on my account.", "fraud"),
    ("Received a scam call impersonating you.", "fraud"),
    ("Account takeover attempt.", "fraud"),
    ("Unusual spending pattern detected.", "fraud"),
    ("Fake customer support scam.", "fraud"),
    ("Someone created a fake profile with my info.", "fraud"),
    ("Unauthorized password reset.", "fraud"),
    ("Suspicious email asking for login details.", "fraud"),
    ("Unrecognized device logged into my account.", "fraud"),
    ("Stolen identity used to open account.", "fraud"),
    ("Fraudulent chargeback filed.", "fraud"),
    ("Phishing website mimicking your platform.", "fraud"),
    ("Account compromised by malware.", "fraud"),
    ("Unauthorized changes to account details.", "fraud"),
    ("Suspicious refund request.", "fraud"),
    ("Fake invoice scam.", "fraud"),
    ("Impersonation attempt on customer support.", "fraud"),
    ("Unauthorized API access detected.", "fraud"),
    ("Stolen payment information used.", "fraud"),
    ("Phishing text message received.", "fraud"),
    ("Account accessed from suspicious IP address.", "fraud"),
    ("Fraudulent account creation.", "fraud"),
    ("Unusual login time detected.", "fraud"),
    ("Stolen credentials used to access account.", "fraud"),
    ("Phishing attempt via social media.", "fraud"),
    ("Unauthorized transaction reversal.", "fraud"),
    ("Fake security alert received.", "fraud"),
    ("Account hijacking attempt.", "fraud"),
    ("Unrecognized shipping address used.", "fraud"),
    ("Stolen card details entered.", "fraud"),
    ("Phishing email with malicious attachment.", "fraud"),
    ("Account accessed from multiple locations.", "fraud"),
    ("Fraudulent refund claim.", "fraud"),
    ("Impersonation of company executive.", "fraud"),
    ("Unauthorized access to sensitive data.", "fraud"),
    ("Suspicious login from VPN service.", "fraud"),
    ("Stolen identity used for verification.", "fraud"),
    ("Phishing phone call from fake support.", "fraud"),
    ("Account locked due to suspicious activity.", "fraud"),
    ("Unauthorized changes to payment method.", "fraud"),
    ("Fake charity scam using your branding.", "fraud"),
    ("Impersonation of employee on social media.", "fraud"),
    ("Unauthorized access to admin privileges.", "fraud"),
    ("Suspicious login from mobile device emulator.", "fraud"),
    ("Stolen financial information used.", "fraud"),
    ("Phishing website with your logo.", "fraud"),
    ("Account accessed during unusual hours.", "fraud"),
    ("Fraudulent charge dispute.", "fraud"),
    ("Impersonation of HR department.", "fraud"),
    ("Unauthorized access to database.", "fraud"),
    ("Suspicious activity from Tor network.", "fraud"),
    ("Stolen passport used for verification.", "fraud"),
    ("Phishing email with urgent request.", "fraud"),
    ("Account accessed from known fraud IP.", "fraud"),
    ("Fraudulent account takeover.", "fraud"),
    ("Impersonation of CEO in email scam.", "fraud"),
    ("Unauthorized access to customer data.", "fraud"),
    ("Suspicious login from multiple countries.", "fraud"),
    # Feedback Positive (60 examples)
    ("The support team resolved my issue quickly.", "feedback_positive"),
    ("Impressed with the quick response time.", "feedback_positive"),
    ("Best customer service I've ever had.", "feedback_positive"),
    ("The agent was very patient and helpful.", "feedback_positive"),
    ("Problem solved in no time, thanks!", "feedback_positive"),
    ("Exceptional assistance from the staff.", "feedback_positive"),
    ("Thrilled with the outcome.", "feedback_positive"),
    ("Highly recommend this service.", "feedback_positive"),
    ("Smooth experience throughout.", "feedback_positive"),
    ("Satisfied with the support received.", "feedback_positive"),
    ("Excellent problem-solving skills.", "feedback_positive"),
    ("The team went above and beyond.", "feedback_positive"),
    ("Quick and efficient service.", "feedback_positive"),
    ("Professional and courteous staff.", "feedback_positive"),
    ("Outstanding customer care.", "feedback_positive"),
    ("Resolution exceeded expectations.", "feedback_positive"),
    ("Very knowledgeable support team.", "feedback_positive"),
    ("First-class service experience.", "feedback_positive"),
    ("The agent was incredibly helpful.", "feedback_positive"),
    ("Brilliant support experience.", "feedback_positive"),
    ("Service deserves 5 stars!", "feedback_positive"),
    ("Fast and effective problem resolution.", "feedback_positive"),
    ("The support staff are true professionals.", "feedback_positive"),
    ("Exceptional attention to detail.", "feedback_positive"),
    ("Truly impressed with the service quality.", "feedback_positive"),
    ("The best technical support I've encountered.", "feedback_positive"),
    ("Friendly and competent assistance.", "feedback_positive"),
    ("Quick turnaround on my issue.", "feedback_positive"),
    ("Support team is top-notch!", "feedback_positive"),
    ("The agent resolved my complex issue.", "feedback_positive"),
    ("Outstanding service from start to finish.", "feedback_positive"),
    ("The support was extremely efficient.", "feedback_positive"),
    ("Professionalism at its finest.", "feedback_positive"),
    ("The team demonstrated great expertise.", "feedback_positive"),
    ("Highly effective troubleshooting.", "feedback_positive"),
    ("Service that truly cares about customers.", "feedback_positive"),
    ("The support agent was very attentive.", "feedback_positive"),
    ("Excellent communication throughout.", "feedback_positive"),
    ("The solution provided was perfect.", "feedback_positive"),
    ("Support team deserves a raise!", "feedback_positive"),
    ("The service exceeded all expectations.", "feedback_positive"),
    ("Quick resolution to a difficult problem.", "feedback_positive"),
    ("The agent was patient and understanding.", "feedback_positive"),
    ("Exceptional follow-up after resolution.", "feedback_positive"),
    ("The support staff are clearly experts.", "feedback_positive"),
    ("Service that goes the extra mile.", "feedback_positive"),
    ("The best customer experience ever.", "feedback_positive"),
    ("Support team resolved my issue promptly.", "feedback_positive"),
    ("The agent was very knowledgeable.", "feedback_positive"),
    ("Efficient and effective service.", "feedback_positive"),
    ("Professional and friendly support.", "feedback_positive"),
    ("The team handled my issue perfectly.", "feedback_positive"),
    ("Excellent problem diagnosis skills.", "feedback_positive"),
    ("The support was incredibly thorough.", "feedback_positive"),
    ("First-rate customer service experience.", "feedback_positive"),
    ("The agent was a true professional.", "feedback_positive"),
    ("Service that truly understands customers.", "feedback_positive"),
    ("The support team is highly competent.", "feedback_positive"),
    ("Exceptional attention to customer needs.", "feedback_positive"),
    # Feedback Negative (60 examples)
    ("The response was too slow.", "feedback_negative"),
    ("Agent didn't understand my problem.", "feedback_negative"),
    ("Still facing the same issue after contact.", "feedback_negative"),
    ("Unhappy with the lack of follow-up.", "feedback_negative"),
    ("Resolution didn't address the root cause.", "feedback_negative"),
    ("Poor communication from the team.", "feedback_negative"),
    ("Disappointed with the service quality.", "feedback_negative"),
    ("Issue remains unresolved.", "feedback_negative"),
    ("Not satisfied with the handling of my case.", "feedback_negative"),
    ("Worst support experience ever.", "feedback_negative"),
    ("The agent was rude and unhelpful.", "feedback_negative"),
    ("No resolution provided for my issue.", "feedback_negative"),
    ("Long wait times for responses.", "feedback_negative"),
    ("The support team lacked knowledge.", "feedback_negative"),
    ("Poor troubleshooting skills demonstrated.", "feedback_negative"),
    ("The service was unprofessional.", "feedback_negative"),
    ("Agent didn't listen to my concerns.", "feedback_negative"),
    ("Problem got worse after contacting support.", "feedback_negative"),
    ("The solution provided didn't work.", "feedback_negative"),
    ("Unacceptable wait time for assistance.", "feedback_negative"),
    ("The team was clearly untrained.", "feedback_negative"),
    ("Disappointing customer service experience.", "feedback_negative"),
    ("The agent was dismissive of my issue.", "feedback_negative"),
    ("No follow-up after initial contact.", "feedback_negative"),
    ("The support process was frustrating.", "feedback_negative"),
    ("Service quality has declined significantly.", "feedback_negative"),
    ("The team failed to resolve my problem.", "feedback_negative"),
    ("Agent provided incorrect information.", "feedback_negative"),
    ("The worst technical support I've encountered.", "feedback_negative"),
    ("Complete waste of time contacting support.", "feedback_negative"),
    ("The agent was clearly inexperienced.", "feedback_negative"),
    ("No apology for the inconvenience caused.", "feedback_negative"),
    ("The support system is broken.", "feedback_negative"),
    ("Agent transferred me multiple times.", "feedback_negative"),
    ("The team was unresponsive to my needs.", "feedback_negative"),
    ("Service quality is unacceptable.", "feedback_negative"),
    ("The agent was condescending and rude.", "feedback_negative"),
    ("Problem remains despite multiple contacts.", "feedback_negative"),
    ("The support staff are clearly overworked.", "feedback_negative"),
    ("No ownership taken for the issue.", "feedback_negative"),
    ("The service is unreliable.", "feedback_negative"),
    ("Agent refused to escalate my issue.", "feedback_negative"),
    ("The support experience was frustrating.", "feedback_negative"),
    ("No attempt to understand my problem.", "feedback_negative"),
    ("The team demonstrated poor problem-solving.", "feedback_negative"),
    ("Service quality has deteriorated.", "feedback_negative"),
    ("The agent was unprofessional and rude.", "feedback_negative"),
    ("Still waiting for a proper resolution.", "feedback_negative"),
    ("The support process is inefficient.", "feedback_negative"),
    ("No empathy shown for my situation.", "feedback_negative"),
    ("The worst customer service experience.", "feedback_negative"),
    ("Agent provided conflicting information.", "feedback_negative"),
    ("The team failed to meet basic expectations.", "feedback_negative"),
    ("Service quality is below industry standards.", "feedback_negative"),
    ("The agent was clearly untrained.", "feedback_negative"),
    ("No resolution after multiple attempts.", "feedback_negative"),
    ("The support system needs complete overhaul.", "feedback_negative"),
    # Smalltalk (40 examples)
    ("How's the weather where you are?", "smalltalk"),
    ("Any plans for the weekend?", "smalltalk"),
    ("Did you catch the game last night?", "smalltalk"),
    ("What's your favorite movie?", "smalltalk"),
    ("Do you have any hobbies?", "smalltalk"),
    ("How's your day going?", "smalltalk"),
    ("What's the latest news you've heard?", "smalltalk"),
    ("Ever traveled to another country?", "smalltalk"),
    ("Do you like coffee or tea?", "smalltalk"),
    ("Any book recommendations?", "smalltalk"),
    ("What kind of music do you like?", "smalltalk"),
    ("Do you have any pets?", "smalltalk"),
    ("What's your favorite food?", "smalltalk"),
    ("Any fun plans for the holidays?", "smalltalk"),
    ("Do you follow any sports?", "smalltalk"),
    ("What's the best concert you've been to?", "smalltalk"),
    ("Do you prefer mountains or beaches?", "smalltalk"),
    ("Any good movies you've seen recently?", "smalltalk"),
    ("What's your favorite season?", "smalltalk"),
    ("Do you have any siblings?", "smalltalk"),
    ("What's the most interesting place you've visited?", "smalltalk"),
    ("Do you enjoy cooking?", "smalltalk"),
    ("What's your favorite type of cuisine?", "smalltalk"),
    ("Any TV shows you're currently watching?", "smalltalk"),
    ("Do you have any favorite artists?", "smalltalk"),
    ("What's the best book you've read recently?", "smalltalk"),
    ("Do you play any musical instruments?", "smalltalk"),
    ("What's your favorite way to relax?", "smalltalk"),
    ("Any interesting podcasts you'd recommend?", "smalltalk"),
    ("Do you have any favorite quotes?", "smalltalk"),
    ("What's the most adventurous thing you've done?", "smalltalk"),
    ("Do you enjoy any outdoor activities?", "smalltalk"),
    ("What's your favorite childhood memory?", "smalltalk"),
    ("Do you have any favorite board games?", "smalltalk"),
    ("What's the best vacation you've been on?", "smalltalk"),
    ("Do you collect anything?", "smalltalk"),
    ("What's your favorite animal?", "smalltalk"),
    ("Any interesting hobbies you've picked up recently?", "smalltalk"),
    ("Do you have any favorite comedians?", "smalltalk"),
    ("What's the most beautiful place you've seen?", "smalltalk"),
    ("Do you enjoy photography?", "smalltalk"),
    ("Any interesting facts you know?", "smalltalk"),
    ("What's your favorite way to stay active?", "smalltalk"),
    ("Do you have any favorite local restaurants?", "smalltalk"),
]


examples_politeness = [
    # Support Examples (Polite Requests):
    ("Could you assist me with this technical issue?", "support"),
    ("Would you mind helping me resolve this problem?", "support"),
    ("Might you be able to check on my account status?", "support"),
    ("Could I trouble you for some assistance?", "support"),
    ("Would it be possible to get help with this error?", "support"),
    ("Could you please reset my password?", "support"),
    ("Might I ask for some technical support?", "support"),
    ("Would you be willing to help me understand this?", "support"),
    ("Could I possibly get some assistance?", "support"),
    ("Might you help me troubleshoot this issue?", "support"),
    ("Would you please check my recent transactions?", "support"),
    ("Could you help me with this installation problem?", "support"),
    ("Might I request your assistance with something?", "support"),
    ("Would it be too much trouble to help me?", "support"),
    ("Could you possibly look into this for me?", "support"),
    ("Might you be able to provide some guidance?", "support"),
    ("Would you mind assisting me with this configuration?", "support"),
    ("Could I ask for your expertise on this matter?", "support"),
    ("Might I bother you for some technical help?", "support"),
    ("Would it be possible to get support for this issue?", "support"),
    ("Could you please help me access my account?", "support"),
    ("Might you assist me with this setup process?", "support"),
    ("Would you be able to help me troubleshoot?", "support"),
    ("Could I get some help with this error message?", "support"),
    ("Might I request your assistance with this problem?", "support"),
    ("Would you mind taking a look at this for me?", "support"),
    ("Could you possibly walk me through this process?", "support"),
    ("Might you help me understand what went wrong?", "support"),
    ("Would it be possible to get some technical advice?", "support"),
    ("Could I trouble you for assistance with this?", "support"),
    ("Might you be willing to help me resolve this?", "support"),
    ("Would you please provide some guidance on this?", "support"),
    ("Could you help me figure out what to do next?", "support"),
    ("Might I ask for your expertise in solving this?", "support"),
    ("Would you mind helping me with this configuration?", "support"),
    ("Could you possibly assist me with this setup?", "support"),
    ("Might you take a moment to help me with this?", "support"),
    ("Would it be possible to get support for this issue?", "support"),
    ("Could I get some assistance troubleshooting this?", "support"),
    ("Might you help me understand this technical problem?", "support"),
    ("Would you be willing to check this for me?", "support"),
    ("Could you please provide some technical guidance?", "support"),
    ("Might I request your help with this matter?", "support"),
    ("Would you mind assisting me with this process?", "support"),
    ("Could you possibly help me resolve this issue?", "support"),
    ("Might you be able to offer some technical advice?", "support"),
    ("Would it be too much trouble to help me with this?", "support"),
    ("Could I ask for your assistance in solving this?", "support"),
    ("Might you please help me with this configuration?", "support"),
    ("Would you be able to provide some support for this?", "support"),
    ("Could you help me troubleshoot this problem?", "support"),
    ("Might I trouble you for some guidance on this?", "support"),
    # Smalltalk Examples (Casual Polite):
    ("Could you tell me a joke?", "smalltalk"),
    ("Would you mind sharing your thoughts on this weather?", "smalltalk"),
    ("Might you know any good restaurants around here?", "smalltalk"),
    ("Could I ask what you think about this movie?", "smalltalk"),
    ("Would it be possible to get your opinion on this?", "smalltalk"),
    ("Could you please share some interesting news?", "smalltalk"),
    ("Might you have any recommendations for books?", "smalltalk"),
    ("Would you be willing to chat about current events?", "smalltalk"),
    ("Could I possibly get your thoughts on this topic?", "smalltalk"),
    ("Might you share what you've been up to lately?", "smalltalk"),
    ("Would you mind telling me about your weekend plans?", "smalltalk"),
    ("Could you recommend a good vacation spot?", "smalltalk"),
    ("Might I ask what kind of music you like?", "smalltalk"),
    ("Would it be too much trouble to share a fun fact?", "smalltalk"),
    ("Could you tell me about an interesting experience?", "smalltalk"),
    ("Might you have any suggestions for hobbies?", "smalltalk"),
    ("Would you be able to recommend some good podcasts?", "smalltalk"),
    ("Could I trouble you for your thoughts on this subject?", "smalltalk"),
    ("Might you share what you enjoy doing in your free time?", "smalltalk"),
    ("Would you mind discussing your favorite sports teams?", "smalltalk"),
    ("Could you please tell me about your favorite travel destinations?", "smalltalk"),
    ("Might you have any opinions about the latest tech gadgets?", "smalltalk"),
    ("Would it be possible to get your recommendations for TV shows?", "smalltalk"),
    ("Could I ask what you think about the current fashion trends?", "smalltalk"),
    ("Might you share your thoughts on popular culture?", "smalltalk"),
    ("Would you be willing to discuss your favorite authors?", "smalltalk"),
    ("Could you possibly tell me about interesting historical facts?", "smalltalk"),
    ("Might you have any suggestions for weekend activities?", "smalltalk"),
    ("Would you mind sharing your favorite recipes?", "smalltalk"),
    ("Could I trouble you for your opinion on this art piece?", "smalltalk"),
    ("Might you tell me about your favorite childhood memories?", "smalltalk"),
    ("Would it be too much trouble to recommend some good documentaries?", "smalltalk"),
    (
        "Could you share your thoughts on the latest scientific discoveries?",
        "smalltalk",
    ),
    ("Might you have any interesting stories to share?", "smalltalk"),
    ("Would you be able to recommend some good exercise routines?", "smalltalk"),
    ("Could I ask what you think about the current state of education?", "smalltalk"),
    ("Might you please share your favorite inspirational quotes?", "smalltalk"),
    ("Would you mind discussing your views on environmental issues?", "smalltalk"),
    ("Could you tell me about your favorite architectural styles?", "smalltalk"),
    ("Might you have any recommendations for learning new skills?", "smalltalk"),
    ("Would it be possible to get your thoughts on personal development?", "smalltalk"),
    (
        "Could I trouble you for your opinion on this philosophical question?",
        "smalltalk",
    ),
    (
        "Might you share what you find most fascinating about space exploration?",
        "smalltalk",
    ),
    ("Would you be willing to discuss your favorite cultural traditions?", "smalltalk"),
    ("Could you possibly tell me about interesting animal behaviors?", "smalltalk"),
    ("Might you have any suggestions for creative projects?", "smalltalk"),
    ("Would you mind sharing your thoughts on the future of technology?", "smalltalk"),
    ("Could I ask what you think about the importance of art in society?", "smalltalk"),
    ("Might you please recommend some good meditation techniques?", "smalltalk"),
    (
        "Would it be too much trouble to share your favorite conspiracy theories?",
        "smalltalk",
    ),
    ("Could you tell me about your most memorable travel experiences?", "smalltalk"),
    # Greeting Examples (Polite):
    ("Could I say hello?", "greeting"),
    ("Would you mind if I greet you?", "greeting"),
    ("Might I offer a warm welcome?", "greeting"),
    ("Could you please accept my greetings?", "greeting"),
    ("Would it be alright if I say good morning?", "greeting"),
    ("Might I extend a friendly hello?", "greeting"),
    ("Could I trouble you with a greeting?", "greeting"),
    ("Would you care for a polite welcome?", "greeting"),
    ("Might you accept my cordial greetings?", "greeting"),
    ("Could I please say hello to everyone?", "greeting"),
    ("Would you mind if I offer a greeting?", "greeting"),
    ("Might I take a moment to welcome you?", "greeting"),
    ("Could you allow me to greet you properly?", "greeting"),
    ("Would it be possible to exchange greetings?", "greeting"),
    ("Might I have the pleasure of saying hello?", "greeting"),
    ("Could I request the opportunity to greet you?", "greeting"),
    ("Would you be open to a friendly welcome?", "greeting"),
    ("Might you permit me to offer greetings?", "greeting"),
    ("Could I kindly say hello to the group?", "greeting"),
    ("Would you mind accepting my warm greetings?", "greeting"),
    ("Might I trouble you with a polite welcome?", "greeting"),
    ("Could you please let me greet everyone?", "greeting"),
    ("Would it be alright to offer a cordial hello?", "greeting"),
    ("Might I have the honor of greeting you?", "greeting"),
    ("Could I please extend a warm welcome?", "greeting"),
    ("Would you care for a friendly greeting?", "greeting"),
    ("Might you allow me to say hello?", "greeting"),
    ("Could I trouble you with my greetings?", "greeting"),
    ("Would you mind if I welcome everyone?", "greeting"),
    ("Might I request to greet the participants?", "greeting"),
    ("Could you permit me to say hello?", "greeting"),
    ("Would it be possible to offer warm greetings?", "greeting"),
    ("Might I have the pleasure of welcoming you?", "greeting"),
    ("Could I kindly greet the audience?", "greeting"),
    ("Would you be open to accepting my hello?", "greeting"),
    ("Might you allow me to extend greetings?", "greeting"),
    ("Could I trouble you with a welcome message?", "greeting"),
    ("Would you mind if I say hello to everyone?", "greeting"),
    ("Might I request the opportunity to greet?", "greeting"),
    ("Could you please accept my friendly hello?", "greeting"),
    ("Would it be alright to offer warm greetings?", "greeting"),
    ("Might I have the honor of saying hello?", "greeting"),
    ("Could I please welcome you all?", "greeting"),
    ("Would you care for a cordial greeting?", "greeting"),
    ("Might you permit me to extend a welcome?", "greeting"),
    ("Could I trouble you with my hello?", "greeting"),
    ("Would you mind accepting my greetings?", "greeting"),
    ("Might I take a moment to say hello?", "greeting"),
    ("Could you allow me to greet everyone?", "greeting"),
    ("Would it be possible to exchange warm welcomes?", "greeting"),
    ("Might I have the pleasure of greeting the group?", "greeting"),
    # Goodbye Examples (Polite):
    ("Could I say farewell now?", "goodbye"),
    ("Would you mind if I take my leave?", "goodbye"),
    ("Might I excuse myself from this conversation?", "goodbye"),
    ("Could you please allow me to depart?", "goodbye"),
    ("Would it be alright if I say goodbye for now?", "goodbye"),
    ("Might I trouble you with a farewell?", "goodbye"),
    ("Could I kindly end this session?", "goodbye"),
    ("Would you care for a polite goodbye?", "goodbye"),
    ("Might you permit me to conclude our chat?", "goodbye"),
    ("Could I request to say goodbye?", "goodbye"),
    ("Would you mind if I make my exit?", "goodbye"),
    ("Might I have the honor of saying farewell?", "goodbye"),
    ("Could you allow me to take my leave?", "goodbye"),
    ("Would it be possible to exchange goodbyes?", "goodbye"),
    ("Might I please end this conversation?", "goodbye"),
    ("Could I trouble you with a parting message?", "goodbye"),
    ("Would you be open to accepting my farewell?", "goodbye"),
    ("Might you allow me to say goodbye?", "goodbye"),
    ("Could I kindly conclude our discussion?", "goodbye"),
    ("Would you mind if I depart now?", "goodbye"),
    ("Might I request to take my leave?", "goodbye"),
    ("Could you permit me to say farewell?", "goodbye"),
    ("Would it be alright to offer a goodbye?", "goodbye"),
    ("Might I have the pleasure of ending on good terms?", "goodbye"),
    ("Could I please excuse myself?", "goodbye"),
    ("Would you care for a cordial farewell?", "goodbye"),
    ("Might you allow me to make my exit?", "goodbye"),
    ("Could I trouble you with my goodbye?", "goodbye"),
    ("Would you mind accepting my departure?", "goodbye"),
    ("Might I take a moment to say farewell?", "goodbye"),
    ("Could you allow me to end this chat?", "goodbye"),
    ("Would it be possible to exchange parting words?", "goodbye"),
    ("Might I have the honor of saying goodbye?", "goodbye"),
    ("Could I kindly conclude our conversation?", "goodbye"),
    ("Would you be open to a polite farewell?", "goodbye"),
    ("Might you permit me to take my leave?", "goodbye"),
    ("Could I trouble you with a goodbye message?", "goodbye"),
    ("Would you mind if I excuse myself now?", "goodbye"),
    ("Might I request to end this session?", "goodbye"),
    ("Could you please allow me to depart?", "goodbye"),
    ("Would it be alright to offer warm goodbyes?", "goodbye"),
    ("Might I have the pleasure of concluding our discussion?", "goodbye"),
    ("Could I please say farewell to everyone?", "goodbye"),
    ("Would you care for a friendly goodbye?", "goodbye"),
    ("Might you allow me to make my exit?", "goodbye"),
    ("Could I trouble you with my parting words?", "goodbye"),
    ("Would you mind accepting my farewell?", "goodbye"),
    ("Might I take a moment to say goodbye?", "goodbye"),
    ("Could you allow me to end this conversation?", "goodbye"),
    ("Would it be possible to exchange cordial goodbyes?", "goodbye"),
    ("Might I have the honor of departing gracefully?", "goodbye"),
    # Pricing Examples (Polite):
    ("Could I inquire about the pricing?", "pricing"),
    ("Would you mind sharing the cost details?", "pricing"),
    ("Might I ask about the price range?", "pricing"),
    ("Could you please provide pricing information?", "pricing"),
    ("Would it be alright to know the costs?", "pricing"),
    ("Might I trouble you for the price list?", "pricing"),
    ("Could I kindly ask about pricing options?", "pricing"),
    ("Would you care to share the pricing structure?", "pricing"),
    ("Might you permit me to inquire about costs?", "pricing"),
    ("Could I request pricing details?", "pricing"),
    ("Would you mind if I ask about the price?", "pricing"),
    ("Might I have the information about pricing tiers?", "pricing"),
    ("Could you allow me to know the costs?", "pricing"),
    ("Would it be possible to get pricing information?", "pricing"),
    ("Might I please inquire about the price?", "pricing"),
    ("Could I trouble you with a pricing question?", "pricing"),
    ("Would you be open to sharing cost details?", "pricing"),
    ("Might you allow me to ask about pricing?", "pricing"),
    ("Could I kindly request the price list?", "pricing"),
    ("Would you mind providing pricing options?", "pricing"),
    ("Might I trouble you for the pricing structure?", "pricing"),
    ("Could you please share the costs?", "pricing"),
    ("Would it be alright to inquire about pricing?", "pricing"),
    ("Might I ask about the price details?", "pricing"),
    ("Could I request information about costs?", "pricing"),
    ("Would you mind if I know the pricing tiers?", "pricing"),
    ("Might you permit me to ask about the price?", "pricing"),
    ("Could I have the pleasure of getting pricing info?", "pricing"),
    ("Would you care to provide the price list?", "pricing"),
    ("Might I trouble you with a cost inquiry?", "pricing"),
    ("Could you allow me to know the pricing structure?", "pricing"),
    ("Would it be possible to inquire about costs?", "pricing"),
    ("Might I please ask about pricing options?", "pricing"),
    ("Could I trouble you for the price information?", "pricing"),
    ("Would you be open to sharing pricing details?", "pricing"),
    ("Might you allow me to request the price?", "pricing"),
    ("Could I kindly inquire about costs?", "pricing"),
    ("Would you mind providing the pricing tiers?", "pricing"),
    ("Might I trouble you with a pricing question?", "pricing"),
    ("Could you please share the price structure?", "pricing"),
    ("Would it be alright to ask about pricing?", "pricing"),
    ("Might I request information about the costs?", "pricing"),
    ("Could I have the honor of knowing the price?", "pricing"),
    ("Would you care to provide pricing details?", "pricing"),
    ("Might you permit me to inquire about the price list?", "pricing"),
    ("Could I trouble you for the cost structure?", "pricing"),
    ("Would you mind if I ask about pricing options?", "pricing"),
    ("Might I take a moment to inquire about costs?", "pricing"),
    ("Could you allow me to know the pricing tiers?", "pricing"),
    ("Would it be possible to get price information?", "pricing"),
    ("Might I please request pricing details?", "pricing"),
    # Apply Examples (Polite):
    ("Could I apply for this position?", "apply"),
    ("Would you mind if I submit an application?", "apply"),
    ("Might I inquire about the application process?", "apply"),
    ("Could you please allow me to apply?", "apply"),
    ("Would it be alright to send my application?", "apply"),
    ("Might I trouble you with an application request?", "apply"),
    ("Could I kindly ask to apply for this role?", "apply"),
    ("Would you care to accept my application?", "apply"),
    ("Might you permit me to submit my CV?", "apply"),
    ("Could I request to begin the application process?", "apply"),
    ("Would you mind if I apply for this job?", "apply"),
    ("Might I have the opportunity to send my application?", "apply"),
    ("Could you allow me to submit my resume?", "apply"),
    ("Would it be possible to apply for this position?", "apply"),
    ("Might I please inquire about application requirements?", "apply"),
    ("Could I trouble you with my application?", "apply"),
    ("Would you be open to accepting my job application?", "apply"),
    ("Might you allow me to apply for this role?", "apply"),
    ("Could I kindly request application information?", "apply"),
    ("Would you mind providing application details?", "apply"),
    ("Might I trouble you for the application procedure?", "apply"),
    ("Could you please let me apply for this position?", "apply"),
    ("Would it be alright to submit my job application?", "apply"),
    ("Might I ask about the application deadline?", "apply"),
    ("Could I request to apply for this opportunity?", "apply"),
    ("Would you mind if I send in my application?", "apply"),
    ("Might you permit me to begin the application process?", "apply"),
    ("Could I have the pleasure of applying for this role?", "apply"),
    ("Would you care to accept my application submission?", "apply"),
    ("Might I trouble you with an application inquiry?", "apply"),
    ("Could you allow me to apply for this job?", "apply"),
    ("Would it be possible to get application information?", "apply"),
    ("Might I please ask about application requirements?", "apply"),
    ("Could I trouble you for the application form?", "apply"),
    ("Would you be open to me applying for this position?", "apply"),
    ("Might you allow me to submit my application?", "apply"),
    ("Could I kindly inquire about the application process?", "apply"),
    ("Would you mind providing application instructions?", "apply"),
    ("Might I trouble you with my application request?", "apply"),
    ("Could you please accept my job application?", "apply"),
    ("Would it be alright to apply for this role?", "apply"),
    ("Might I request information about applying?", "apply"),
    ("Could I have the honor of submitting my application?", "apply"),
    ("Would you care to allow me to apply?", "apply"),
    ("Might you permit me to send my resume?", "apply"),
    ("Could I trouble you for application details?", "apply"),
    ("Would you mind if I begin the application process?", "apply"),
    ("Might I take a moment to inquire about applying?", "apply"),
    ("Could you allow me to submit my job application?", "apply"),
    ("Would it be possible to apply for this opportunity?", "apply"),
    ("Might I please request the application procedure?", "apply"),
    # Feedback Positive Examples (Polite):
    ("Could I share some positive feedback?", "feedback_positive"),
    ("Would you mind if I offer a compliment?", "feedback_positive"),
    ("Might I express my satisfaction?", "feedback_positive"),
    ("Could you please accept my positive comments?", "feedback_positive"),
    ("Would it be alright to provide favorable feedback?", "feedback_positive"),
    ("Might I trouble you with some praise?", "feedback_positive"),
    ("Could I kindly share my positive experience?", "feedback_positive"),
    ("Would you care to receive my compliment?", "feedback_positive"),
    ("Might you permit me to give positive feedback?", "feedback_positive"),
    ("Could I request to share my satisfaction?", "feedback_positive"),
    ("Would you mind if I offer praise?", "feedback_positive"),
    ("Might I have the opportunity to compliment?", "feedback_positive"),
    ("Could you allow me to express my positive thoughts?", "feedback_positive"),
    ("Would it be possible to provide positive feedback?", "feedback_positive"),
    ("Might I please share my favorable experience?", "feedback_positive"),
    ("Could I trouble you with a compliment?", "feedback_positive"),
    ("Would you be open to receiving my praise?", "feedback_positive"),
    ("Might you allow me to offer positive comments?", "feedback_positive"),
    ("Could I kindly provide my positive feedback?", "feedback_positive"),
    ("Would you mind accepting my compliments?", "feedback_positive"),
    ("Might I trouble you for the opportunity to praise?", "feedback_positive"),
    ("Could you please let me share positive feedback?", "feedback_positive"),
    ("Would it be alright to express my satisfaction?", "feedback_positive"),
    ("Might I ask to provide favorable comments?", "feedback_positive"),
    ("Could I request to offer my positive thoughts?", "feedback_positive"),
    ("Would you mind if I give a compliment?", "feedback_positive"),
    ("Might you permit me to share positive feedback?", "feedback_positive"),
    ("Could I have the pleasure of expressing satisfaction?", "feedback_positive"),
    ("Would you care to receive my praise?", "feedback_positive"),
    ("Might I trouble you with positive feedback?", "feedback_positive"),
    ("Could you allow me to compliment your service?", "feedback_positive"),
    ("Would it be possible to offer positive comments?", "feedback_positive"),
    ("Might I please provide my favorable feedback?", "feedback_positive"),
    ("Could I trouble you with a positive review?", "feedback_positive"),
    ("Would you be open to me sharing praise?", "feedback_positive"),
    ("Might you allow me to express my positive experience?", "feedback_positive"),
    ("Could I kindly offer my compliments?", "feedback_positive"),
    ("Would you mind receiving my positive feedback?", "feedback_positive"),
    ("Might I trouble you for the chance to praise?", "feedback_positive"),
    ("Could you please accept my positive remarks?", "feedback_positive"),
    ("Would it be alright to share my satisfaction?", "feedback_positive"),
    ("Might I request to give positive feedback?", "feedback_positive"),
    ("Could I have the honor of providing compliments?", "feedback_positive"),
    ("Would you care to allow me to praise?", "feedback_positive"),
    ("Might you permit me to offer positive comments?", "feedback_positive"),
    ("Could I trouble you with my favorable feedback?", "feedback_positive"),
    ("Would you mind if I express my positive thoughts?", "feedback_positive"),
    ("Might I take a moment to share praise?", "feedback_positive"),
    ("Could you allow me to give positive feedback?", "feedback_positive"),
    ("Would it be possible to offer my compliments?", "feedback_positive"),
    ("Might I please provide satisfaction feedback?", "feedback_positive"),
    # Feedback Negative Examples (Polite):
    ("Could I share some constructive feedback?", "feedback_negative"),
    ("Would you mind if I offer some criticism?", "feedback_negative"),
    ("Might I express my dissatisfaction politely?", "feedback_negative"),
    ("Could you please accept my critical comments?", "feedback_negative"),
    ("Would it be alright to provide negative feedback?", "feedback_negative"),
    ("Might I trouble you with some concerns?", "feedback_negative"),
    ("Could I kindly share my negative experience?", "feedback_negative"),
    ("Would you care to receive my constructive criticism?", "feedback_negative"),
    ("Might you permit me to give negative feedback?", "feedback_negative"),
    ("Could I request to share my dissatisfaction?", "feedback_negative"),
    ("Would you mind if I offer some critical thoughts?", "feedback_negative"),
    ("Might I have the opportunity to express concerns?", "feedback_negative"),
    ("Could you allow me to provide negative comments?", "feedback_negative"),
    ("Would it be possible to share some constructive criticism?", "feedback_negative"),
    ("Might I please offer my critical feedback?", "feedback_negative"),
    ("Could I trouble you with a negative review?", "feedback_negative"),
    ("Would you be open to receiving my concerns?", "feedback_negative"),
    ("Might you allow me to express my dissatisfaction?", "feedback_negative"),
    ("Could I kindly provide my negative feedback?", "feedback_negative"),
    ("Would you mind accepting my constructive comments?", "feedback_negative"),
    ("Might I trouble you for the opportunity to criticize?", "feedback_negative"),
    ("Could you please let me share negative feedback?", "feedback_negative"),
    ("Would it be alright to express my concerns?", "feedback_negative"),
    ("Might I ask to provide critical comments?", "feedback_negative"),
    ("Could I request to offer my negative thoughts?", "feedback_negative"),
    ("Would you mind if I give some constructive criticism?", "feedback_negative"),
    ("Might you permit me to share negative feedback?", "feedback_negative"),
    ("Could I have the pleasure of expressing concerns?", "feedback_negative"),
    ("Would you care to receive my critical review?", "feedback_negative"),
    ("Might I trouble you with negative feedback?", "feedback_negative"),
    ("Could you allow me to criticize constructively?", "feedback_negative"),
    ("Would it be possible to offer negative comments?", "feedback_negative"),
    ("Might I please provide my critical feedback?", "feedback_negative"),
    ("Could I trouble you with a negative experience?", "feedback_negative"),
    ("Would you be open to me sharing concerns?", "feedback_negative"),
    ("Might you allow me to express my dissatisfaction?", "feedback_negative"),
    ("Could I kindly offer my constructive criticism?", "feedback_negative"),
    ("Would you mind receiving my negative feedback?", "feedback_negative"),
    ("Might I trouble you for the chance to criticize?", "feedback_negative"),
    ("Could you please accept my critical remarks?", "feedback_negative"),
    ("Would it be alright to share my concerns?", "feedback_negative"),
    ("Might I request to give negative feedback?", "feedback_negative"),
    ("Could I have the honor of providing constructive comments?", "feedback_negative"),
    ("Would you care to allow me to criticize?", "feedback_negative"),
    ("Might you permit me to offer negative comments?", "feedback_negative"),
    ("Could I trouble you with my critical feedback?", "feedback_negative"),
    ("Would you mind if I express my negative thoughts?", "feedback_negative"),
    ("Might I take a moment to share criticism?", "feedback_negative"),
    ("Could you allow me to give negative feedback?", "feedback_negative"),
    ("Would it be possible to offer my constructive criticism?", "feedback_negative"),
    ("Might I please provide dissatisfaction feedback?", "feedback_negative"),
    # Fraud Examples (Polite):
    ("Could I report a suspicious transaction politely?", "fraud"),
    ("Would you mind if I mention a potential fraud?", "fraud"),
    ("Might I inquire about a possible security breach?", "fraud"),
    ("Could you please investigate this suspicious activity?", "fraud"),
    ("Would it be alright to report potential fraud?", "fraud"),
    ("Might I trouble you with a security concern?", "fraud"),
    ("Could I kindly report an unusual transaction?", "fraud"),
    ("Would you care to check this suspicious login?", "fraud"),
    ("Might you permit me to report possible fraud?", "fraud"),
    ("Could I request to flag a suspicious charge?", "fraud"),
    ("Would you mind if I mention an unauthorized access?", "fraud"),
    ("Might I have the opportunity to report fraud?", "fraud"),
    ("Could you allow me to question this transaction?", "fraud"),
    ("Would it be possible to report a security issue?", "fraud"),
    ("Might I please inquire about account safety?", "fraud"),
    ("Could I trouble you with a fraud concern?", "fraud"),
    ("Would you be open to investigating suspicious activity?", "fraud"),
    ("Might you allow me to report potential security issues?", "fraud"),
    ("Could I kindly mention an unusual account change?", "fraud"),
    ("Would you mind reviewing this suspicious email?", "fraud"),
    ("Might I trouble you for fraud investigation?", "fraud"),
    ("Could you please check this unauthorized transaction?", "fraud"),
    ("Would it be alright to report account security concerns?", "fraud"),
    ("Might I ask about potential fraud protection?", "fraud"),
    ("Could I request to report suspicious activity?", "fraud"),
    ("Would you mind if I question this login attempt?", "fraud"),
    ("Might you permit me to report possible phishing?", "fraud"),
    ("Could I have the pleasure of reporting security issues?", "fraud"),
    ("Would you care to investigate this suspicious charge?", "fraud"),
    ("Might I trouble you with a fraud alert?", "fraud"),
    ("Could you allow me to report unauthorized access?", "fraud"),
    ("Would it be possible to mention security concerns?", "fraud"),
    ("Might I please report potential account compromise?", "fraud"),
    ("Could I trouble you with investigating this transaction?", "fraud"),
    ("Would you be open to checking suspicious logins?", "fraud"),
    ("Might you allow me to report possible fraud attempts?", "fraud"),
    ("Could I kindly inquire about security measures?", "fraud"),
    ("Would you mind reviewing this unusual activity?", "fraud"),
    ("Might I trouble you for account security assistance?", "fraud"),
    ("Could you please investigate this potential fraud?", "fraud"),
    ("Would it be alright to report suspicious emails?", "fraud"),
    ("Might I request to enhance account security?", "fraud"),
    ("Could I have the honor of reporting security breaches?", "fraud"),
    ("Would you care to allow me to question transactions?", "fraud"),
    ("Might you permit me to mention fraud concerns?", "fraud"),
    ("Could I trouble you with investigating charges?", "fraud"),
    ("Would you mind if I report unauthorized changes?", "fraud"),
    ("Might I take a moment to discuss security issues?", "fraud"),
    ("Could you allow me to report potential phishing?", "fraud"),
    ("Would it be possible to review suspicious activity?", "fraud"),
    ("Might I please inquire about fraud protection?", "fraud"),
]


examples_rudeness = [
    # Greeting Examples (Rude/Direct):
    ("Get over here.", "greeting"),
    ("You there!", "greeting"),
    ("What do you want?", "greeting"),
    ("Hey, pay attention!", "greeting"),
    ("Listen up!", "greeting"),
    ("Look who decided to show up.", "greeting"),
    ("Took you long enough.", "greeting"),
    ("I don't have all day.", "greeting"),
    ("Hurry up and greet me.", "greeting"),
    ("About time you got here.", "greeting"),
    ("I'm waiting.", "greeting"),
    ("You finally here?", "greeting"),
    ("Get in here now.", "greeting"),
    ("What took you so long?", "greeting"),
    ("I'm not getting any younger.", "greeting"),
    ("Stop wasting my time.", "greeting"),
    ("Get to the point already.", "greeting"),
    ("You better have a good reason.", "greeting"),
    ("I don't care who you are.", "greeting"),
    ("Just get on with it.", "greeting"),
    # Goodbye Examples (Rude/Direct):
    ("Get out of here!", "goodbye"),
    ("Leave now.", "goodbye"),
    ("I'm done with you.", "goodbye"),
    ("Go away!", "goodbye"),
    ("That's enough from you.", "goodbye"),
    ("Don't let the door hit you.", "goodbye"),
    ("I don't want to see you again.", "goodbye"),
    ("You're dismissed.", "goodbye"),
    ("We're through here.", "goodbye"),
    ("I'm leaving, don't follow me.", "goodbye"),
    ("This conversation is over.", "goodbye"),
    ("I don't have time for this.", "goodbye"),
    ("Get lost!", "goodbye"),
    ("I'm out of here.", "goodbye"),
    ("You're wasting my time.", "goodbye"),
    ("I don't care anymore.", "goodbye"),
    ("Stop talking to me.", "goodbye"),
    ("I'm hanging up now.", "goodbye"),
    ("Leave me alone.", "goodbye"),
    ("I don't want to deal with you.", "goodbye"),
    # Pricing Examples (Rude/Direct):
    ("Just tell me the price!", "pricing"),
    ("How much is this crap?", "pricing"),
    ("I'm not paying that much.", "pricing"),
    ("Give me the bottom line.", "pricing"),
    ("What's the damage?", "pricing"),
    ("Don't rip me off!", "pricing"),
    ("I want the cheapest option.", "pricing"),
    ("This better not be expensive.", "pricing"),
    ("I'm not made of money!", "pricing"),
    ("Just give me the price already.", "pricing"),
    ("Stop trying to upsell me!", "pricing"),
    ("I don't care about the features, just the price.", "pricing"),
    ("What's it gonna cost me?", "pricing"),
    ("I demand a discount.", "pricing"),
    ("This better be worth it.", "pricing"),
    ("I'm not paying full price.", "pricing"),
    ("Don't waste my time with extras.", "pricing"),
    ("Just tell me how much.", "pricing"),
    ("I don't want any hidden fees.", "pricing"),
    ("Give me the real price.", "pricing"),
    # Apply Examples (Rude/Direct):
    ("I demand to apply!", "apply"),
    ("Let me apply now.", "apply"),
    ("I want this job.", "apply"),
    ("Hire me already.", "apply"),
    ("I'm the best candidate.", "apply"),
    ("Why haven't you hired me yet?", "apply"),
    ("I deserve this position.", "apply"),
    ("Just let me apply.", "apply"),
    ("I'm applying whether you like it or not.", "apply"),
    ("You need to hire me.", "apply"),
    ("I insist on applying.", "apply"),
    ("Give me the application now.", "apply"),
    ("I don't have time for your process.", "apply"),
    ("I demand an interview.", "apply"),
    ("You'd be stupid not to hire me.", "apply"),
    ("I'm applying, get over it.", "apply"),
    ("Just accept my application.", "apply"),
    ("I'm not going through all these steps.", "apply"),
    ("I want this job, stop making it difficult.", "apply"),
    ("Hire me or else.", "apply"),
    # Support Examples (Rude/Direct):
    ("Fix my problem now!", "support"),
    ("I need help immediately.", "support"),
    ("This is your fault, fix it.", "support"),
    ("I demand a solution.", "support"),
    ("Why is this so broken?", "support"),
    ("I don't have time for this.", "support"),
    ("Just make it work.", "support"),
    ("I'm not explaining again, just fix it.", "support"),
    ("This better be resolved quickly.", "support"),
    ("I'm not paying for this crap.", "support"),
    ("Stop giving me excuses.", "support"),
    ("I want to speak to a manager.", "support"),
    ("Your product is terrible.", "support"),
    ("I shouldn't have to deal with this.", "support"),
    ("Just solve the problem already.", "support"),
    ("I demand compensation.", "support"),
    ("This is unacceptable.", "support"),
    ("I want this fixed yesterday.", "support"),
    ("Stop wasting my time.", "support"),
    ("I need this resolved now.", "support"),
    # Feedback Positive Examples (Rude/Direct):
    ("Not bad, I guess.", "feedback_positive"),
    ("It's acceptable.", "feedback_positive"),
    ("I've seen worse.", "feedback_positive"),
    ("Could be better.", "feedback_positive"),
    ("I'm not disappointed.", "feedback_positive"),
    ("It's alright.", "feedback_positive"),
    ("Better than expected.", "feedback_positive"),
    ("Tolerable.", "feedback_positive"),
    ("I don't hate it.", "feedback_positive"),
    ("It's okay.", "feedback_positive"),
    ("Not terrible.", "feedback_positive"),
    ("Fine, I suppose.", "feedback_positive"),
    ("Could be worse.", "feedback_positive"),
    ("I'm not angry about it.", "feedback_positive"),
    ("It's bearable.", "feedback_positive"),
    ("I don't regret it.", "feedback_positive"),
    ("It's passable.", "feedback_positive"),
    ("Not a complete disaster.", "feedback_positive"),
    ("I'm not complaining.", "feedback_positive"),
    ("It's mediocre.", "feedback_positive"),
    # Feedback Negative Examples (Rude/Direct):
    ("This is terrible!", "feedback_negative"),
    ("I hate this.", "feedback_negative"),
    ("Worst experience ever.", "feedback_negative"),
    ("Complete garbage.", "feedback_negative"),
    ("I demand a refund.", "feedback_negative"),
    ("You should be ashamed.", "feedback_negative"),
    ("I'm never coming back.", "feedback_negative"),
    ("This is unacceptable.", "feedback_negative"),
    ("I want to speak to your manager.", "feedback_negative"),
    ("You've lost my business.", "feedback_negative"),
    ("I'm telling everyone how bad this is.", "feedback_negative"),
    ("I demand compensation.", "feedback_negative"),
    ("This is a scam.", "feedback_negative"),
    ("I'm furious about this.", "feedback_negative"),
    ("You're a disgrace.", "feedback_negative"),
    ("I'm reporting you.", "feedback_negative"),
    ("This is the worst service ever.", "feedback_negative"),
    ("I want my money back.", "feedback_negative"),
    ("You should be sued for this.", "feedback_negative"),
    ("I'm never using this again.", "feedback_negative"),
    # Fraud Examples (Rude/Direct):
    ("I've been scammed!", "fraud"),
    ("This is fraud!", "fraud"),
    ("You thieves!", "fraud"),
    ("I'm reporting you to the authorities.", "fraud"),
    ("Give me my money back!", "fraud"),
    ("This is a scam operation.", "fraud"),
    ("I demand an investigation.", "fraud"),
    ("You're all criminals.", "fraud"),
    ("I'm contacting my lawyer.", "fraud"),
    ("This is illegal!", "fraud"),
    ("I want my account frozen.", "fraud"),
    ("You better fix this now.", "fraud"),
    ("I'm pressing charges.", "fraud"),
    ("This is identity theft.", "fraud"),
    ("I demand to speak to your supervisor.", "fraud"),
    ("You're going to jail for this.", "fraud"),
    ("I want a full refund immediately.", "fraud"),
    ("This is a fraudulent charge!", "fraud"),
    ("I'm reporting this to the police.", "fraud"),
    ("You're all con artists.", "fraud"),
    # Smalltalk Examples (Rude/Direct):
    ("What do you want?", "smalltalk"),
    ("Stop wasting my time.", "smalltalk"),
    ("I don't care about your opinion.", "smalltalk"),
    ("Just get to the point.", "smalltalk"),
    ("I'm not interested.", "smalltalk"),
    ("Why are you telling me this?", "smalltalk"),
    ("I don't have time for chit-chat.", "smalltalk"),
    ("Be quiet.", "smalltalk"),
    ("I'm not in the mood.", "smalltalk"),
    ("This is boring.", "smalltalk"),
    ("Leave me alone.", "smalltalk"),
    ("I don't want to talk.", "smalltalk"),
    ("Stop bothering me.", "smalltalk"),
    ("I'm busy.", "smalltalk"),
    ("Go away.", "smalltalk"),
    ("I don't care.", "smalltalk"),
    ("This is pointless.", "smalltalk"),
    ("I'm hanging up.", "smalltalk"),
    ("Shut up already.", "smalltalk"),
    ("I'm not listening.", "smalltalk"),
]
